### ISSUE TITLE
Create namespace for Cognitive Atlas terms

### ISSUE THREAD

**Issue by alyssadai** [neurobagel/bagel-cli#106]
- [x] Update `field_preamble` for the context in pheno_utils.py 
https://github.com/neurobagel/bagel-cli/blob/d5762fc508a469b6f87f1745eb7fd2e9bb3263d4/bagel/pheno_utils.py#L15-L22
  with `"cogAtlas": "https://www.cognitiveatlas.org/task/id/"`
- [x] update context of `example_synthetic.jsonld`

**Comment by alyssadai** [comment]
@surchs since the Cognitive Atlas doesn't seem to provide controlled terms the way that snomed/nidm does, are we planning to use its [API](https://www.cognitiveatlas.org/api/v-alpha/task) / [Python module](https://cogat-python.readthedocs.io/en/latest/getting_started.html#functions) to "search" for term IDs corresponding to human-readable strings of task names? And store the term IDs, e.g. https://www.cognitiveatlas.org/task/id/trm_56674133b666c/, in our graph?

**Comment by surchs** [comment]
yes, I think that's the plan for now. I'm not sure what you mean by "not the same way as snomed/nidm". CogAtlas does actually provide IRIs that you can go to (i.e. the id of the term is a real website where you can learn more about the term), and that's not true of all nidm terms, and even most of snomed-ct terms. 

They do not provide a graph ready format, but we can go and talk to them about that. For now, the fact that we can unambiguously refer to a term and its definition by the task id should be enough for our purposes. We will likely have to build a graph version of these terms for ourselves, so that we can use the human readable labels

**Comment by alyssadai** [comment]
Ah, okay, I think I understand. 👍 Will implement as above.
