### ISSUE TITLE
CI should not install in dev mode

### ISSUE THREAD

**Issue by surchs** [neurobagel/bagel-cli#376]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Expected Behavior

My CI tests run using the same environment I would expect to have when using the tools as a user. 

### Current Behavior

The CI runs our tests after install the tool in [dev-mode](https://pip.pypa.io/en/latest/topics/local-project-installs/#editable-installs):

https://github.com/neurobagel/bagel-cli/blob/c4a4616a7578e1ca15b2c9ab4a738ceb15574b29/.github/workflows/test.yml#L26

For the docker image, we build things correctly

https://github.com/neurobagel/bagel-cli/blob/c4a4616a7578e1ca15b2c9ab4a738ceb15574b29/Dockerfile#L11

### Error message

The main issue here seems to be that relative paths (e.g. to submodules in the repo) are resolving correctly
when the tests run in dev-mode, but they no longer resolve correctly when the installed regularly.

This is currently causing all kinds of issues around the newly introduced submodule dependencies. but the 
underlying problem is that we test in a different install mode than we run our tools

### Environment

- OS:
- Python/Node version:

### Anything else?

Related to #375

**Comment by alyssadai** [comment]
For clarification, I don't think that

https://github.com/neurobagel/bagel-cli/blob/c4a4616a7578e1ca15b2c9ab4a738ceb15574b29/.github/workflows/test.yml#L26

is the main reason why the tests succeed in our workflow, but rather the fact that we checkout the entire repo as part of the workflow. So, the working directory where the tests run (and the test CLI app, as part of the tests) has all the relative paths set up as expected by the code.

This is in contrast to running the installed CLI directly, which looks instead at the installed `bagel/` package directory inside `site-packages`, and so depends on whatever is available there. (I don't think the tests ever actually "install" the CLI?)

This can be confirmed by doing a bare Python installation of all dependencies & the `bagel` package in non-editable mode, and then running 

1. a `bagel derivatives` command - **fails** because `pipeline-catalog` is not in the `bagel/` installation directory
2. all tests (`python -m pytest`) - **succeeds**

That all being said, I agree that it would be a good idea to not install in editable mode for the purpose of the tests, just to get as close to the production environment as we can.
