### ISSUE TITLE
For BIDS subjects with only one session (and therefore no `ses` subdirectory), create a new session object with label `01`

### ISSUE THREAD

**Issue by alyssadai** [neurobagel/bagel-cli#82]
- [x] Newly created session should have an obvious name that distinguishes it from BIDS-created sessions -`ses-nb01`
- [x] Add a comment in the portion of the code that will handle this edge case (and probably also in the test that is assuring it works) as to why we have decided to do this, and maybe also a TODO note to come back and revisit this

**Comment by alyssadai** [comment]
@surchs just confirming that we still want to do this to be in line with what we decided for the api, https://github.com/neurobagel/api/pull/81#issuecomment-1428088045?

**Comment by surchs** [comment]
I think yes @alyssadai, but it's a bit tricky. Because if we do this without also changing the underlying BIDS data by adding a `ses-01` directory, then we are breaking our existing promise of "all information in the graph is just a representation of what's on disk". On the other hand, if we do decide to change the BIDS dataset (or in the future expect that others do so before using our tools), then we break a different existing promise of "we don't change your existing data, keep doing what you're doing".

I see the reason for being consistent in our modeling and creating a session if none exists. Maybe for now we can add some clarity to what we're doing by:
- documenting this behaviour of adding a session in the graph even if none exists in the file system prominently in the user facing docs
- calling the newly created session something obvious like `ses-neurobagelcreated`
- leaving a comment in the portion of the code that will handle this edge case (and probably also in the test that is assuring it works) as to why we have decided to do this, and maybe also a `TODO` note to come back and revisit this

What do you think?

**Comment by alyssadai** [comment]
Good points about changing the data on disk. The implementation I'm currently working on indeed creates a new session in the BIDS dataset representation _without_ changing anything in the filesystem.

Will follow your suggestions for keeping the behaviour clear in the code 🙂
